### ISSUE TITLE
didn't work for me

### ISSUE THREAD

**Issue by asangansi** [niutech/typescript-compile#2]
how come it works on github but not on my system?
Thanks

**Comment by niutech** [comment]
The demo doesn't work on file:// protocol, because it loads external .ts files via XHR and it is disallowed there. However, you can remove the line: `<script type="text/typescript" src="demo.ts"></script>` from the demo or run it on a local web server.

**Comment by asangansi** [comment]
Thanks. That was helpful, have it working now.
