### ISSUE TITLE
Is typescript-compile a compiled version of the typescript compiler?

### ISSUE THREAD

**Issue by mnapoli** [niutech/typescript-compile#4]
Typescript compiler is written in Typescript. So is typescript-compile the official Typescript compiler compiled into Javascript? (hope the question makes sense)

I just wonder if this project is a complete rewrite of the original compiler, or if it reuses it.

**Comment by ComFreek** [comment]
I'm not the project owner (I started a similar project) but it's only an interface to the original TypeScript compiler code.

**Comment by niutech** [comment]
The file _typescript.js_ is the original TypeScript compiler script version [0.8.0](http://typescript.codeplex.com/SourceControl/changeset/view/fe3bc0bfce1f#bin/typescript.js), but you can replace it with the newer version [0.8.1](http://typescript.codeplex.com/SourceControl/changeset/view/c283ca0bbc9d#bin%2ftypescript.js).

**Comment by mnapoli** [comment]
OK thank you it makes more sense to me now
